"""empty message

Revision ID: 1285e50ad63a
Revises: 6aac43779b30
Create Date: 2020-03-24 12:07:42.275090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1285e50ad63a'
down_revision = '6aac43779b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lable__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('leval', sa.Integer(), nullable=True),
    sa.Column('cost_perform', sa.Integer(), nullable=True),
    sa.Column('appearance', sa.Integer(), nullable=True),
    sa.Column('applicability', sa.Integer(), nullable=True),
    sa.Column('laber', sa.String(length=16), nullable=True),
    sa.Column('is_labled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lable__data_is_labled'), 'lable__data', ['is_labled'], unique=False)
    op.create_index(op.f('ix_lable__data_laber'), 'lable__data', ['laber'], unique=False)
    op.create_index(op.f('ix_lable__data_source_id'), 'lable__data', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lable__data_source_id'), table_name='lable__data')
    op.drop_index(op.f('ix_lable__data_laber'), table_name='lable__data')
    op.drop_index(op.f('ix_lable__data_is_labled'), table_name='lable__data')
    op.drop_table('lable__data')
    # ### end Alembic commands ###
