"""empty message

Revision ID: 5c4a7cc7d0e2
Revises: e0a7f115c88a
Create Date: 2020-03-24 13:16:35.700811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c4a7cc7d0e2'
down_revision = 'e0a7f115c88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('leval', sa.Integer(), nullable=True),
    sa.Column('cost_perform', sa.Integer(), nullable=True),
    sa.Column('appearance', sa.Integer(), nullable=True),
    sa.Column('applicability', sa.Integer(), nullable=True),
    sa.Column('laber', sa.String(length=16), nullable=True),
    sa.Column('is_labled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_data_is_labled'), 'label_data', ['is_labled'], unique=False)
    op.create_index(op.f('ix_label_data_laber'), 'label_data', ['laber'], unique=False)
    op.create_index(op.f('ix_label_data_source_id'), 'label_data', ['source_id'], unique=False)
    op.drop_index('ix_lable_data_is_labled', table_name='lable_data')
    op.drop_index('ix_lable_data_laber', table_name='lable_data')
    op.drop_index('ix_lable_data_source_id', table_name='lable_data')
    op.drop_table('lable_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lable_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('leval', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cost_perform', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appearance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('applicability', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laber', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('is_labled', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_lable_data_source_id', 'lable_data', ['source_id'], unique=False)
    op.create_index('ix_lable_data_laber', 'lable_data', ['laber'], unique=False)
    op.create_index('ix_lable_data_is_labled', 'lable_data', ['is_labled'], unique=False)
    op.drop_index(op.f('ix_label_data_source_id'), table_name='label_data')
    op.drop_index(op.f('ix_label_data_laber'), table_name='label_data')
    op.drop_index(op.f('ix_label_data_is_labled'), table_name='label_data')
    op.drop_table('label_data')
    # ### end Alembic commands ###
