"""empty message

Revision ID: 6aac43779b30
Revises: b5a45440b11d
Create Date: 2020-03-24 12:06:43.795418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aac43779b30'
down_revision = 'b5a45440b11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lable__data_is_labled', table_name='lable__data')
    op.drop_index('ix_lable__data_laber', table_name='lable__data')
    op.drop_index('ix_lable__data_source_id', table_name='lable__data')
    op.drop_table('lable__data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lable__data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('leval', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cost_perform', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appearance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('applicability', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laber', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('is_labled', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_lable__data_source_id', 'lable__data', ['source_id'], unique=False)
    op.create_index('ix_lable__data_laber', 'lable__data', ['laber'], unique=False)
    op.create_index('ix_lable__data_is_labled', 'lable__data', ['is_labled'], unique=False)
    # ### end Alembic commands ###
