"""empty message

Revision ID: b5a45440b11d
Revises: 44ac09b089b6
Create Date: 2020-03-24 11:52:57.802979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5a45440b11d'
down_revision = '44ac09b089b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lable__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('leval', sa.Integer(), nullable=True),
    sa.Column('cost_perform', sa.Integer(), nullable=True),
    sa.Column('appearance', sa.Integer(), nullable=True),
    sa.Column('applicability', sa.Integer(), nullable=True),
    sa.Column('laber', sa.String(length=16), nullable=True),
    sa.Column('is_labled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lable__data_is_labled'), 'lable__data', ['is_labled'], unique=False)
    op.create_index(op.f('ix_lable__data_laber'), 'lable__data', ['laber'], unique=False)
    op.create_index(op.f('ix_lable__data_source_id'), 'lable__data', ['source_id'], unique=False)
    op.drop_index('ix_lable_evalution_is_labled', table_name='lable_evalution')
    op.drop_index('ix_lable_evalution_laber', table_name='lable_evalution')
    op.drop_index('ix_lable_evalution_source_id', table_name='lable_evalution')
    op.drop_table('lable_evalution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lable_evalution',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('leval', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cost_perform', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appearance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('applicability', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('laber', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('is_labled', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_lable_evalution_source_id', 'lable_evalution', ['source_id'], unique=False)
    op.create_index('ix_lable_evalution_laber', 'lable_evalution', ['laber'], unique=False)
    op.create_index('ix_lable_evalution_is_labled', 'lable_evalution', ['is_labled'], unique=False)
    op.drop_index(op.f('ix_lable__data_source_id'), table_name='lable__data')
    op.drop_index(op.f('ix_lable__data_laber'), table_name='lable__data')
    op.drop_index(op.f('ix_lable__data_is_labled'), table_name='lable__data')
    op.drop_table('lable__data')
    # ### end Alembic commands ###
